title: Kaylea Nelson
email: kaylea.nelson@yale.edu
description: >-
    Kaylea Nelson. Research Computing.
github_username:  kayleanelson
google_analytics: G-VKYKT1GRWP

exclude:
- Gemfile
- Gemfile.lock
